# Basic Information
Title: Maibam Rakesh Singh
Position: Pathways in Data Sciences, Mathematical Statistics &
Affiliation: Mathematical Statistical Physics
Email: maibamrakeshsingh31@gmail.com

# Search Engine Optimization (SEO)
Keywords: data science, statistical physics, research, academic homepage, machine learning, physics
Description: Academic homepage of Maibam Rakesh Singh, showcasing research at the intersection of Data Science and Statistical Physics.
Canonical: https://minimal-light-theme.yliu.me/

# Links
#Google_Scholar: #https://scholar.google.com/
CV_Link: assets/files/curriculum_vitae.pdf
GitHub_Link: https://github.com/maibamrakeshsingh
LinkedIn: https://www.linkedin.com/in/maibamrakeshsingh/
#Twitter: https://twitter.com/

# Images
Avatar: ./assets/img/rake.png
Favicon: ./assets/img/favicon.png
Favicon_Dark: ./assets/img/favicon-dark.png

# Footnote
Enable_Footnote: true

# Auto Dark Mode
Auto_Dark_Mode: true

# Font
Font: "Serif" # Options: "Serif" or "Sans Serif"

# Google Analytics ID
Google_Analytics: UA-111540567-4

# Remote Theme for GitHub Pages
Remote_Theme: yaoyao-liu/minimal-light

# Excluded Files
Exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
  - .gitignore
